In [2]:
from bs4 import BeautifulSoup as bs
import pandas as pd
import requests
import pymysql
pymysql.install_as_MySQLdb()
from sqlalchemy import create_engine

url = 'https://www.jumia.com.ng/mlp-stay-connected-deals/smartphones/'
page = requests.get(url)
soup = bs(page.content, 'html5lib')
#print(soup.prettify())
table = soup.find('div', attrs={'class': '-paxs row _no-g _4cl-3cm-shs'})
#print(table.prettify())
articles = table.findAll('article', attrs={'class': 'prd _fb col c-prd'})
#print(articles[1].prettify())
#items = []
df = pd.DataFrame(columns=['name', 'discounted_price', 'original_price', 'discount', 'rating'])
for phone in articles:
    item = {}
    item['name'] = phone.find('h3', attrs={'class': "name"}).text
    discount_price = phone.find('div', attrs={'class': 'prc'})
    if discount_price is not None:
       item['discounted_price'] = discount_price.text.replace("₦ ", "")
    original_price = phone.find('div', attrs={'class': 'old'})
    if original_price is not None:
       item['original_price'] = original_price.text.replace("₦ ", "")
    discount = phone.find('div', attrs={'class': 'bdg _dsct _sm'})
    if discount is not None:
       item['discount'] = discount.text
    rating = phone.find('div', class_='stars _s')
    if rating is not None:
        item['rating'] = rating.contents[0] # or .find_next(text=True)
    else:
        item['rating'] = ""
   
    df = df.append(item, ignore_index=True)
try:
    engine = create_engine('mysql://root:@localhost/univelcity')
    with engine.begin() as connection:
        df.to_sql(name='web_scrapping_information', con=connection, if_exists='append', index=False)
except Exception as e:
    print(e)
print("we are done!")

SyntaxError: invalid non-printable character U+00A0 (782715883.py, line 19)

In [4]:
import numpy as np
np_array = np.array([1,2,4,6])
print("Array size:", np_array.size)
print("Array dtype:", np_array.dtype)
print("Array shape:", np_array.shape)
print("Array dimension:", np_array.shape)


Array size: 4
Array dtype: int32
Array shape: (4,)


In [6]:
np_arrange_array = np.arange(2,20,2)
print(np_arrange_array)

np_arrange_array = np_arrange_array.reshape(3,3)
print(np_arrange_array)

[ 2  4  6  8 10 12 14 16 18]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [11]:
array = np.arange(2,37,2)
array_reshaped = array.reshape(3,3,2)
print(array)
print(array.shape)
print(array.size)
print("Array n dimension:", array.ndim)
print("\n----After reshape----")
print(array_reshaped)
print(array_reshaped.shape)
print(array_reshaped.size)
print("Array n dimesion: ",array_reshaped.ndim)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36]
(18,)
18
Array n dimension: 1

----After reshape----
[[[ 2  4]
  [ 6  8]
  [10 12]]

 [[14 16]
  [18 20]
  [22 24]]

 [[26 28]
  [30 32]
  [34 36]]]
(3, 3, 2)
18
Array n dimesion:  3


In [12]:
array = np.arange(2,20,2)
print(array.size)

9


In [24]:
array = np.arange(1,49,2)
print(array.size)
array_resphaped = array.reshape(2,4,3)
print(array_reshaped)print(array.shape)
print(array.size)
print("Array n dimension:", array.ndim)
print("\n----After reshape----")
print(array_reshaped)
print(array_reshaped.shape)
print(array_reshaped.size)
print("Array n dimesion: ",array_reshaped.ndim)



24
[[[ 2  4]
  [ 6  8]
  [10 12]]

 [[14 16]
  [18 20]
  [22 24]]

 [[26 28]
  [30 32]
  [34 36]]]


In [26]:
#numpy linespace
arr = np.linspace(2,5,5)
print(arr)

[2.   2.75 3.5  4.25 5.  ]


In [28]:
ones_array = np.ones(6)
print(ones_array.reshape(2,3))

zeros = np.zeros(10)
print(zeros)

[[1. 1. 1.]
 [1. 1. 1.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [31]:
array = np.arange(2,20)
print(array)

array = np.append(array, 40)
print(array)

array = np.delete(array, 17)
print(array)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 40]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 40]


In [36]:
array_random = np.random.rand(10)
print(array_random)
sorted_array = np.sort(array_random)
print(sorted_array)

random_item = np.random.random()
print("Random number", round(random_item * 100,2))

[0.73729334 0.30569767 0.39801126 0.32662984 0.29185868 0.05472079
 0.88263634 0.03321606 0.93542642 0.61480613]
[0.03321606 0.05472079 0.29185868 0.30569767 0.32662984 0.39801126
 0.61480613 0.73729334 0.88263634 0.93542642]
Random number 15.57


In [37]:
array_a = np.arange(1,10)
array_b = np.arange(11,20)
print("array a: ", array_a)
print("array b: ", array_b)
array_c = array_b + array_a
print("array_c:", array_c)


array a:  [1 2 3 4 5 6 7 8 9]
array b:  [11 12 13 14 15 16 17 18 19]
array_c: [12 14 16 18 20 22 24 26 28]
